name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-j6me.onrender.com/